import os
import json
from pathlib import Path
from telegram import Bot


ASSETS_DIR = Path("src/assets")
JSON_PATH = Path("src/config/generated/photo_ids.json")
PY_PATH = Path("src/config/generated/photo_ids.py")
BOT_TOKEN = "8103234203:AAH-nB2QOC4E-ubMEmYSBxPwFOym4k2YDD0"
CHAT_ID = "1134038010"

if not BOT_TOKEN:
    raise ValueError("BOT_TOKEN environment variable not set")
if not CHAT_ID:
    raise ValueError("PHOTO_TARGET_CHAT_ID environment variable not set")


async def upload_all_photos():
    bot = Bot(BOT_TOKEN)

    if JSON_PATH.exists():
        with open(JSON_PATH, encoding="utf-8") as f:
            photo_ids = json.load(f)
    else:
        photo_ids = {}

    for file in sorted(ASSETS_DIR.glob("*.[jp][pn]g")):
        key = file.stem
        if key in photo_ids:
            print(f"⏭ Пропускаем {key} — уже загружен.")
            continue

        with file.open("rb") as f:
            try:
                msg = await bot.send_photo(chat_id=CHAT_ID, photo=f)
                file_id = msg.photo[-1].file_id
                photo_ids[key] = file_id
                print(f"Загружен {key}: {file_id}")
            except Exception as e:
                print(f"Ошибка при загрузке {key}: {e}")

    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Сохраняем JSON
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(photo_ids, f, ensure_ascii=False, indent=2)

    # Сохраняем PY-файл
    with open(PY_PATH, "w", encoding="utf-8") as f:
        f.write("# Autogenerated by photo_loader.py\n")
        f.write("PHOTO_IDS = {\n")
        for k, v in photo_ids.items():
            f.write(f'    "{k}": "{v}",\n')
        f.write("}\n")

    print(f"\n📁 Сохранено в {JSON_PATH} и {PY_PATH}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(upload_all_photos())
